### ISSUE TITLE
Indicator / feature generation

### ISSUE THREAD

**Issue by mfeldt** [MykytaPetrenko/Forex_DQN#1]
Hi MykytaPetrenko,

  looks good, and as far as I understand them the results look good, too. Almost too impressive...
What is the way the indicator/feature columns "RelativeHLC #Bn" are computed? Are you sure no *future* information is slipping into rows through them?

**Comment by MykytaPetrenko** [comment]
Hi, mfeldt! Results are not good enough cause in this spread is not used in this tester. If we take into account real spread results will be quite negative. It's just first attempt to make something in this area. 
Relative HLC are not conected with future. They connected only with current prices and ATR. 

RelativeHigh = (High - Open)/ATR(n)
RelativeLow = (Open - Low)/ATR(n)
RelativePositiveClose = (Close - Open)/ATR(n) if Close > Open; else equals to zero
RelativeNegativeClose =  (Open- Close)/ATR(n) if Close < Open; else equals to zero

https://github.com/MykytaPetrenko/RelativeHLC
I find this features some better than prices in case of machine learning.
